import JSZip from "jszip";
import { describe, expect, it } from "vitest";
import {
  createPackMcmeta,
  getAllPresets,
  getFunctionName,
  getFunctionPath,
  voxelModelToDataPackZip
} from "@/lib/voxel";

function getSetblockLines(content: string) {
  return content.split("\n").filter((line) => line.startsWith("setblock "));
}

describe("datapack export", () => {
  const [model] = getAllPresets();

  it("creates valid pack.mcmeta JSON with Minecraft 1.21.1 defaults", () => {
    const packMcmeta = JSON.parse(createPackMcmeta()) as {
      pack: {
        pack_format: number;
        description: string;
      };
    };

    expect(packMcmeta.pack.pack_format).toBe(48);
    expect(packMcmeta.pack.description).toBe("Generated by BlockForge");
  });

  it("uses the default blockforge namespace and 1.21+ function directory", () => {
    expect(getFunctionName(model)).toBe("medieval_tower");
    expect(getFunctionPath(model)).toBe(
      "data/blockforge/function/build/medieval_tower.mcfunction"
    );
  });

  it("creates a Blob zip with pack.mcmeta and the blueprint function", async () => {
    const blob = await voxelModelToDataPackZip(model);
    const zip = await JSZip.loadAsync(blob);
    const functionPath = getFunctionPath(model);

    expect(blob).toBeInstanceOf(Blob);
    expect(zip.file("pack.mcmeta")).not.toBeNull();
    expect(zip.file(functionPath)).not.toBeNull();
  });

  it("writes valid mcfunction content into the datapack zip", async () => {
    const zip = await JSZip.loadAsync(await voxelModelToDataPackZip(model));
    const mcfunction = await zip.file(getFunctionPath(model))?.async("string");

    expect(mcfunction).toBeDefined();
    expect(mcfunction).toContain("setblock");
    expect(mcfunction).not.toContain("/setblock");
    expect(getSetblockLines(mcfunction ?? "")).toHaveLength(model.blocks.length);
  });

  it("includes README.txt when requested", async () => {
    const zip = await JSZip.loadAsync(
      await voxelModelToDataPackZip(model, { includeReadme: true })
    );
    const readme = await zip.file("README.txt")?.async("string");

    expect(readme).toContain("Generated by BlockForge");
    expect(readme).toContain("Target: Minecraft Java Edition 1.21.1");
    expect(readme).toContain("/function blockforge:build/medieval_tower");
  });
});
