import { describe, expect, it } from "vitest";
import { createBlock, getAllPresets, voxelModelToMcFunction } from "@/lib/voxel";
import type { VoxelModel } from "@/types/blueprint";

function getSetblockLines(content: string) {
  return content.split("\n").filter((line) => line.startsWith("setblock "));
}

describe("mcfunction export", () => {
  const [model] = getAllPresets();

  it("outputs a string containing setblock commands", () => {
    const content = voxelModelToMcFunction(model);

    expect(typeof content).toBe("string");
    expect(content).toContain("setblock");
  });

  it("does not prefix commands with a slash", () => {
    const content = voxelModelToMcFunction(model);

    expect(content.split("\n").some((line) => line.startsWith("/setblock"))).toBe(
      false
    );
  });

  it("outputs one setblock command per voxel block", () => {
    const content = voxelModelToMcFunction(model, { includeHeader: true });

    expect(getSetblockLines(content)).toHaveLength(model.blocks.length);
  });

  it("includes Minecraft namespaced block ids in every setblock line", () => {
    const content = voxelModelToMcFunction(model);

    for (const line of getSetblockLines(content)) {
      expect(line).toContain(" minecraft:");
      expect(line).toMatch(/ replace$/);
    }
  });

  it("includes a BlockForge header when requested", () => {
    const content = voxelModelToMcFunction(model, { includeHeader: true });

    expect(content).toContain("# Generated by BlockForge");
    expect(content).toContain(`# Model: ${model.name}`);
    expect(content).toContain(`# Blocks: ${model.blocks.length}`);
  });

  it("uses robust relative coordinate formatting", () => {
    const customModel: VoxelModel = {
      id: "pixel-statue",
      name: "Coordinate Test",
      description: "Tests relative coordinate output.",
      size: {
        width: 2,
        height: 2,
        depth: 2
      },
      blocks: [createBlock(0, 0, 0, "stone"), createBlock(1, 0, 1, "glass")]
    };

    expect(voxelModelToMcFunction(customModel)).toContain(
      "setblock ~ ~ ~ minecraft:stone replace"
    );
    expect(voxelModelToMcFunction(customModel, { origin: { x: -1, y: 0, z: 2 } })).toContain(
      "setblock ~-1 ~ ~2 minecraft:stone replace"
    );
  });
});
