import JSZip from "jszip";
import { createSafeResourcePath } from "@/lib/voxel/exportUtils";
import { voxelModelToMcFunction } from "@/lib/voxel/mcfunction";
import type { VoxelModel } from "@/types/blueprint";

export type DataPackExportOptions = {
  namespace?: string;
  packFormat?: number;
  description?: string;
  includeReadme?: boolean;
};

const defaultDataPackOptions = {
  namespace: "blockforge",
  packFormat: 48,
  description: "Generated by BlockForge"
};

function resolveOptions(options: DataPackExportOptions = {}) {
  return {
    namespace: createSafeResourcePath(
      options.namespace ?? defaultDataPackOptions.namespace
    ),
    packFormat: options.packFormat ?? defaultDataPackOptions.packFormat,
    description: options.description ?? defaultDataPackOptions.description,
    includeReadme: options.includeReadme ?? false
  };
}

export function createPackMcmeta(options: DataPackExportOptions = {}): string {
  const resolvedOptions = resolveOptions(options);

  return JSON.stringify(
    {
      pack: {
        pack_format: resolvedOptions.packFormat,
        description: resolvedOptions.description
      }
    },
    null,
    2
  );
}

export function getFunctionName(model: VoxelModel): string {
  return createSafeResourcePath(model.name);
}

export function getFunctionPath(
  model: VoxelModel,
  namespace = defaultDataPackOptions.namespace
): string {
  const safeNamespace = createSafeResourcePath(namespace);
  return `data/${safeNamespace}/function/build/${getFunctionName(model)}.mcfunction`;
}

function createReadme(model: VoxelModel, namespace: string): string {
  const functionName = getFunctionName(model);

  return [
    "Generated by BlockForge",
    "Target: Minecraft Java Edition 1.21.1",
    "",
    "Install:",
    "1. Copy this zip into .minecraft/saves/<world>/datapacks",
    "2. Run /reload",
    `3. Run /function ${namespace}:build/${functionName}`,
    ""
  ].join("\n");
}

export async function voxelModelToDataPackZip(
  model: VoxelModel,
  options: DataPackExportOptions = {}
): Promise<Blob> {
  const resolvedOptions = resolveOptions(options);
  const zip = new JSZip();

  zip.file("pack.mcmeta", createPackMcmeta(resolvedOptions));
  zip.file(
    getFunctionPath(model, resolvedOptions.namespace),
    voxelModelToMcFunction(model, { includeHeader: true })
  );

  if (resolvedOptions.includeReadme) {
    zip.file("README.txt", createReadme(model, resolvedOptions.namespace));
  }

  return zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: {
      level: 6
    }
  });
}
