import { minecraftBlockIds } from "@/lib/voxel/minecraftBlocks";
import type { VoxelBlock, VoxelModel } from "@/types/blueprint";

export type McFunctionExportOptions = {
  relative?: boolean;
  includeHeader?: boolean;
  origin?: {
    x: number;
    y: number;
    z: number;
  };
};

const defaultOrigin = {
  x: 0,
  y: 0,
  z: 0
};

function formatRelativeCoordinate(value: number) {
  if (value === 0) {
    return "~";
  }

  return `~${value}`;
}

function formatAbsoluteCoordinate(value: number) {
  return String(value);
}

function formatCoordinate(value: number, relative: boolean) {
  return relative ? formatRelativeCoordinate(value) : formatAbsoluteCoordinate(value);
}

function getExportCoordinates(
  block: Pick<VoxelBlock, "x" | "y" | "z">,
  options: Required<Pick<McFunctionExportOptions, "relative" | "origin">>
) {
  return {
    x: options.origin.x + block.x,
    y: options.origin.y + block.y,
    z: options.origin.z + block.z
  };
}

export function voxelModelToMcFunction(
  model: VoxelModel,
  options: McFunctionExportOptions = {}
): string {
  const relative = options.relative ?? true;
  const origin = options.origin ?? defaultOrigin;
  const lines: string[] = [];

  if (options.includeHeader) {
    lines.push(
      "# Generated by BlockForge",
      `# Model: ${model.name}`,
      `# Size: ${model.size.width} x ${model.size.height} x ${model.size.depth}`,
      `# Blocks: ${model.blocks.length}`
    );
  }

  for (const block of model.blocks) {
    const coordinates = getExportCoordinates(block, { relative, origin });
    const x = formatCoordinate(coordinates.x, relative);
    const y = formatCoordinate(coordinates.y, relative);
    const z = formatCoordinate(coordinates.z, relative);
    const minecraftBlockId = minecraftBlockIds[block.block];

    lines.push(`setblock ${x} ${y} ${z} ${minecraftBlockId} replace`);
  }

  return lines.join("\n");
}
